"""20211026_renamed_columns

Revision ID: 6d4bd19d6bf0
Revises: 3a6eafc98acd
Create Date: 2021-10-26 19:09:12.385695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4bd19d6bf0'
down_revision = '3a6eafc98acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('league', sa.String(), nullable=True))
    op.drop_column('team', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('team', 'league')
    # ### end Alembic commands ###
