"""20211026_added_unique_constraints_to_team

Revision ID: b8fbb296f104
Revises: 6d4bd19d6bf0
Create Date: 2021-10-26 19:19:18.592813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8fbb296f104'
down_revision = '6d4bd19d6bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('team', 'league',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('unique_name_league', 'team', ['name', 'league'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_name_league', 'team', type_='unique')
    op.alter_column('team', 'league',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('team', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
