"""20211072_ranamed_group_to_champions_league

Revision ID: 08b68046e1e1
Revises: 6d4bd19d6bf0
Create Date: 2021-10-27 18:29:38.638234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b68046e1e1'
down_revision = '6d4bd19d6bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champions_league_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('match_played', sa.Integer(), nullable=True),
    sa.Column('win', sa.Integer(), nullable=True),
    sa.Column('draw', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('goal_diff', sa.Integer(), nullable=True),
    sa.Column('league_position', sa.Integer(), nullable=True),
    sa.Column('group_names', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('group')
    op.alter_column('team', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('team', 'league',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('unique_name_league', 'team', ['name', 'league'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_name_league', 'team', type_='unique')
    op.alter_column('team', 'league',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('team', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_table('group',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('match_played', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('win', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('draw', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loss', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goals_for', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goals_against', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goal_diff', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('league_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='group_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='group_pkey')
    )
    op.drop_table('champions_league_groups')
    # ### end Alembic commands ###
